# 对标 ARM Cortex-M7（深度面积篇）：拆开研究核的 735 kGE，87% 的面积债锁在一个模块

原创 穆洋 半拍Offbeat

 _2026年6月20日 10:36_

这是《验证工程师用 AI 造 CPU》系列写给做芯片同行(RTL 设计、DV、综合 / 物理实现)的深度分析篇。

上一篇《一周做出对标 ARM M7 的 RISC-V 核》结尾,我留了一张"走向流片"的清单:post-P&R、Cache、调试、中断控制器、PMP、DFT。这两周我把清单逐项做完了——功能补到 `RV32IMAFDCP + B + CLIC + CX`,PMP / 调试全栈 / CLIC 中断 / I$+D$ / 双核一致性 / DCLS 全部落地(功能细节另文展开)。

但这一篇不讲功能。上一篇第 8 节我把核拉去综合,**只量了一个维度:频率**(cell-only TT 角 ~700 MHz、SS 角 ~511 MHz,达标了),我故意留了另一个维度没碰:**面积**。这一篇就把这笔账补上,而且是当面和 M7 算——用门数说话,回答一个最值得专业读者深究的问题:

**功能对位 M7 了、跑分也追平了,为什么硅片面积还比一颗成熟商用核大?面积花在哪、怎么补回来?**

---

## 1. 先给个功能对位:该有的都有了

##   

按上一篇那张"走向流片"清单做下来,这颗核现在是一个**功能上逐项对标(部分超出)M7 的完整核**:misa `0x4000_912F`,8 级双发顺序超标量(就是上一篇的主力核 `r7_core_8d`),产品 SoC 带 I$ + 2 路写回 D$ + TCM + CLINT/CLIC + AHB-Lite。逐项和 M7 摆一起:

|子系统|ARM Cortex-M7|R7（我们）|对位|
|---|---|---|---|
|内存保护|MPU(PMSAv7,≤16 区)|PMP(RISC-V,16 条目)+ 精确 access-fault|对等|
|调试|CoreSight DAP + FPB + DWT|dcsr/dpc + 单步 + DM/DMI + JTAG DTM|精简版|
|中断|NVIC(嵌套 / tail-chaining / 向量)|CLINT + CLIC(嵌套抢占 / 硬件向量 shv / mnxti 尾链)|功能对等|
|Cache / TCM|I/D$ ≤64KB 带 ECC + TCM|I$ 2KB / D$ 2 路写回 / TCM 单周期|我们小、暂无 ECC|
|浮点|FPv5 单+双精度|F 单 + D 双 + **Zfh 半精度**|对等,且我们多 FP16|
|原子|LDREX/STREX 独占监视器|**完整 RV32A AMO + LR/SC**|我们更强|
|安全锁步|DCLS(双核锁步 + 时间错位)|`r7_dcls`<br><br>(逐项对齐 M7)|功能对等(雏形)|
|多核|**单核**<br><br>(DCLS 是冗余非 SMP)|**双核 SMP + snoop-MESI 一致性 + IPI + RVWMO**|M7 根本没有|
|自定义扩展|不允许客户加指令|**R7-CX**<br><br>(对标 Andes ACE,含解耦后台 cx.bgstart / bgget)|M7 没有|

**结论先行**:在"CPU 能不能跑、跑得对不对、功能档位"这一层,R7 已经和 M7 对位,有几项(原子、半精度、多核一致性、自定义扩展)还超出。这一篇不再花篇幅证明这点(前两篇 + 官方一致性套件全过已经说明),而是看一个更硬的维度:**同等功能下,我们这颗核的硅片成本花在哪、为什么离成熟商用核还有距离。**

---

## 2. 门数:735 kGE,对一颗 RV32 研究核偏大

##   

上一篇综合那节,频率量到达标就收手了,没去碰面积——这一篇补上。还是同一套环境:amd7713 服务器,Synopsys DC(compile_ultra,已省面积)+ TSMC 22nm ULL(`tcbn22ullbwp7t30p140` tt0p8v85c,NAND2 = 0.294 µm²),综合同一颗 `r7_core_8d`。拆开我们自己这颗核:

|层级|面积|门当量(kGE)|触发器|
|---|---|---|---|
|整数核(减 FPU)|186,198 µm²|**633 kGE**||
|FPU + FP 寄存器堆|29,752 µm²|**101 kGE**||
|**整核 + FPU**|**215,950 µm²**|**735 kGE**|**39,795**|

> kGE = 面积 ÷ 0.294(NAND2 等效门)。触发器数由本次 DFT scan 插入实测确认:39,795 个时序单元、100% 全扫描(见 §4)。

**735 kGE,对一颗 RV32 研究核来说是偏大的。** 一颗以面积 / 功耗效率著称的成熟同档商用核(M7 正是这类的标杆),同等功能的计算核会比这小得多——它们靠 SRAM 化的存储结构和十年手工优化,把面积压到极致。

那么——**为什么功能对位了,门数还这么大?** 这才是专业读者真正关心的。答案非常集中,而且是个可量化、可修的工程债。

---

## 3. 核心归因:735 kGE 里,一个模块占了 65%

##   

把我们自己这 735 kGE 按模块拆:

![](data:image/svg+xml,%3C%3Fxml%20version='1.0'%20encoding='UTF-8'%3F%3E%3Csvg%20width='1px'%20height='1px'%20viewBox='0%200%201%201'%20version='1.1'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Ctitle%3E%3C/title%3E%3Cg%20stroke='none'%20stroke-width='1'%20fill='none'%20fill-rule='evenodd'%20fill-opacity='0'%3E%3Cg%20transform='translate\(-249.000000,%20-126.000000\)'%20fill='%23FFFFFF'%3E%3Crect%20x='249'%20y='126'%20width='1'%20height='1'%3E%3C/rect%3E%3C/g%3E%3C/g%3E%3C/svg%3E)

**图 1**　R7 core_8d 面积构成。整核 735 kGE 中,分支预测器(BTB/BHT/RAS,触发器堆实现)一个模块占 65%。

|模块|门当量|占整核|
|---|---|---|
|🔴 **分支预测器 `u_bpu`(BTB/BHT/RAS 用触发器堆实现)**|**478 kGE**|**65%**|
|整数 datapath + 控制(双发 + 宽 ISA + 触发器寄存器堆 + PMP×4)|155 kGE|21%|
|FPU + FP 寄存器堆(含半精度 Zfh)|101 kGE|14%|

**整核三分之二的面积,压在一个模块上:分支预测器。**

### 3.1 头号面积债:用触发器堆当存储

###   

R7 的分支预测器结构本身是教科书式的、对的:

- BTB 256 项(取指同拍给目标 PC)
    
- gshare BHT 1024 项(GHR ⊕ PC 索引,2-bit 饱和计数器)
    
- 投机 RAS 8 项
    

问题不在"预测得准不准",在"这几张表**是怎么落到硅片上的**"。我们的 RTL 是行为级写的:

```
logic [TAGW-1:0]   btb_tag   [BTB_ENTRIES];logic [31:0]       btb_target[BTB_ENTRIES];logic [1:0]        bht       [BHT_ENTRIES];
```

综合器看到这种 `reg array`,默认推成 **flip-flop array(触发器堆)**——每一个表项的每一位都是一个 D 触发器,外加一张庞大的读写多路选择网络(取指查 + 双端口训练)。256 项 BTB ×(tag + 32 位 target)+ 1024 项 BHT,全部用触发器实现,就是 **478 kGE,占整核 65%**。

成熟商用核怎么做?**BTAC / BHT 用 SRAM 宏(memory compiler 生成的 RAM)。** 同样容量的预测表,SRAM 的位密度比触发器阵列高一个数量级,而且没有那张读写 mux 网络。这就是为什么一颗面积优化到位的同档核,能在同等预测能力下把取指 / 分支逻辑压到很小,而我们一个 BPU 就吃掉 478 kGE。

这是 **AI 辅助 / 快速原型最典型的物理实现陷阱**:功能描述是对的、行为是对的、跑分是对的、官方一致性全过——但"这张表该是 SRAM"这件事,行为级 RTL 不会自动告诉综合器,综合器也不会自作主张帮你换成 SRAM 宏(那需要显式实例化 memory compiler 的输出)。**功能正确和物理经济,是两件事。**

而且这事和上一篇直接连上了:上一篇第 8 节做 Fmax 综合时,cell-only 的关键路径就压在 BPU(di 是 BTB 写回路径、8d 是晚 ALU → IFQ PC,都在前端)。**当时它是频率的瓶颈,这次它又是面积的第一大户——频率和面积两本账,记在同一个模块上。** 把 BPU 做对(SRAM 化 + 缩表),同时改善面积和频率,一石二鸟。

### 3.2 触发器 39,795 个:深流水 + 双发 + 投机的代价

###   

这次 DFT scan 插入实测,整核 39,795 个时序单元。对一颗 RV32 核,这个数偏高,分解开:

- **BPU 触发器堆**
    
    :256 项 BTB + 1024 项 BHT,本身就是几万个触发器的大头。
    
- **8 级深流水**
    
    :每级都要锁存指令 / 控制 / 数据,双发还要 ×2 槽。
    
- **投机结构**
    
    :解耦取指队列 IFQ、投机 RAS、随流水携带的 BHT 索引(为修 gshare 时序加的)。
    
- **寄存器堆也用触发器**
    
    :整数 4R2W 的 32×32 + FP 寄存器堆,在没有多端口 SRAM 的情况下,综合成触发器 + mux。
    

触发器密,还会**传染到别处**:这次 scan 面积开销 8.8%(全扫描典型 5–10% 的偏高端),根源就是触发器多——而触发器多,又回到 BPU 触发器堆。**一个实现选择的代价,会沿着面积、扫描开销、关键路径一路放大。**

### 3.3 其余部分其实合理

###   

要说句公道话——**除了 BPU,R7 的面积并不离谱**:

- 整数 datapath + 控制 155 kGE:双发(两条执行槽)、更宽的 ISA(I/M/A/F/D/C/B/P 全都要译码和执行单元)、4 个 PMP checker(双发 × insn/data)。这些是功能换来的,合理。
    
- FPU + 寄存器堆 101 kGE:而且我们多了半精度 Zfh 和完整双精度 D 的数据通路。
    

**所以 R7 的面积故事很干净:不是处处臃肿,而是一个模块(BPU)用错了实现方式,贡献了整核 2/3 的面积。** 这是好消息——它是个**集中的、可量化的、可修的**债,不是弥散在全核的系统性低效。

### 3.4 更深一层:为什么会这样

###   

把镜头拉远,我们这颗核和一颗成熟商用核的面积差,本质是两种"核"的差:

- **成熟商用核(M7 这类)是十年手工打磨、面积压到极致的产品**
    
    :预测器 / 寄存器用 SRAM 宏、关键单元用 custom cell、datapath 做过手工资源共享、流程是 area-driven 签核。它卖的就是"在客户的面积 / 功耗预算里塞下一个能打的核"。
    
- **R7 是功能优先、尚未做面积优化的研究核**
    
    :RTL 是行为级描述,综合是 Fmax-driven(为追 450 MHz 目标,compile 甚至会加 buffer 换时序,反而推高组合面积),没有手工 SRAM 化、没有资源共享 pass、没有跑过 area-driven 综合。AI 辅助让我们一周做出功能正确的核,但"把表换成 SRAM、把寄存器堆换成 register file 宏、做面积签核"——这些仍然是要人主导、要工具(memory compiler)、要时间的工程。
    

---

##   

## 4. 这次的综合 + DFT 实测(补充数据)

##   

借这次拆面积,我把完整核(IMAFDCP+B+CX)第一次跑了 DC 综合 + DFT scan 插入,几个新数据:

|项|结果|口径|
|---|---|---|
|**Fmax**|**560 MHz**|TT cell-only;关键路径 `i_dmem_rdata → FPU → o_dmem_wdata`(FPU 主导)|
|**总面积**|219,792 µm²(scan 网表)/ 202,002(非 scan)|TSMC 22ULL,即 §2 的 735 kGE|
|**触发器数**|**39,795**<br><br>(100% 全扫描)|印证 §3.2|
|**DFT scan 链**|8 条均衡(~4,975 / 条),DFT Compiler license 可用|sequential DRC 0 违例|
|**scan 面积开销**|**8.8%**<br><br>(flop premium +33%)|触发器密 → 偏高端|

两个诚实边界,专业读者会问:

- **Fmax 是 cell-only**
    
    (无线延迟 / P&R),偏乐观;而且这次综合脚本没带 FPU 的 multicycle 约束,`mem → FPU → mem` 这条大概率过约束,560 还能再抠。
    
- **DFT 还差 async-reset 的 test 控制**
    
    :这次 scan 插入报了 31,611 条 C26 违例(异步复位被当 data)——这是异步复位设计做 ATPG 前的标准待办,不是 scan 插入失败。
    

---

##   

## 5. 后续工作目标与重点

##   

数据把优先级排得很清楚。按"面积 / 性价比杠杆"从大到小:

### P0(头号 action item):BPU SRAM 化 / 缩表

把 BTB/BHT/RAS 从触发器堆改成 **SRAM 宏 / 缩小表深**。BPU 面积能降一个数量级,整核 **735 → ~290 kGE**——把"一颗研究核偏大的面积"直接拉进成熟同档核的量级。这是面积的头号杠杆,且同时缓解 Fmax 关键路径(BPU),一石二鸟。**做完这一件,整篇文章的面积故事就改写了。**

![](data:image/svg+xml,%3C%3Fxml%20version='1.0'%20encoding='UTF-8'%3F%3E%3Csvg%20width='1px'%20height='1px'%20viewBox='0%200%201%201'%20version='1.1'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3Ctitle%3E%3C/title%3E%3Cg%20stroke='none'%20stroke-width='1'%20fill='none'%20fill-rule='evenodd'%20fill-opacity='0'%3E%3Cg%20transform='translate\(-249.000000,%20-126.000000\)'%20fill='%23FFFFFF'%3E%3Crect%20x='249'%20y='126'%20width='1'%20height='1'%3E%3C/rect%3E%3C/g%3E%3C/g%3E%3C/svg%3E)

**图 2**　P0 面积杠杆。把分支预测器从触发器堆换成 SRAM,BPU 从 478 → ~30 kGE,整核 735 → ~290 kGE(−61%)。

### P1:面积效率与 area-driven 综合

- 寄存器堆(整数 / FP)评估用 register-file 宏或多端口 SRAM。
    
- datapath 资源共享(双发两槽的 ALU / 乘法器复用评估)。
    
- 跑一遍 area-driven 综合 pass(现在全是 Fmax-driven,组合面积被时序优化推高)。
    

### P2:补"产品化外壳"里和正确性相关的部分

- **ECC**
    
    :cache / TCM 的 RAM 加 SECDED(部分已有,补全)。
    
- **低功耗**
    
    :clock gating、WIC / 多级睡眠(目前完全没做)。
    
- **trace 调试外围**
    
    (可选,看是否进交付):成熟商用核那套 ETM/ITM/TPIU trace 是我们最大的纯缺失,但研究核可以按需取舍。
    

### P3:流片工程量(真正离"可流片"的距离)

- **DFT 补 async-reset test 控制**
    
    (本次 C26 发现的)、**MBIST**。
    
- **真实 post-P&R Fmax / STA / 物理签核**
    
    ——仍卡在 P&R 工具(ICC2 / Innovus)+ TSMC PDK NDA 的采购上。
    
- 顺手:给综合 SDC 补上 `mem → FPU → mem` 的 FPU multicycle 约束,把 560 MHz 抠回去一些。
    

---

##   

## 6. 结语:面积、频率、跑分,是几个独立的故事

##   

回到开头那个问题——**功能对位了,为什么面积还比成熟商用核大?**

整核 2/3 的面积来自**一个模块——分支预测器用触发器堆而不是 SRAM**。这是 AI 辅助 / 快速原型典型的物理实现债:功能全对、跑分追平、一致性全过,但"这张表该是 SRAM"这件事没有被表达出来。剩下的(双发宽 ISA datapath、FPU)其实都合理。

对做芯片的同行,这篇真正想留下的是三句话:

1. **面积、频率、跑分,是几个正交的轴。**
    
     一个核可以跑分对标 M7、频率对标 M7,面积却大几倍——评估时要把 gate 分解摊开看,任何一个指标单独拿出来都会骗人。
    
2. **AI 辅助能极快地做出"功能正确、验证充分、跑分对标"的核**
    
    ——这部分前两篇已经证明;但**物理经济性(SRAM 化、资源共享、面积 / 功耗签核)仍然是人主导的工程**,而且恰恰是研究核离"可流片商用 IP"最实在的那道坎。
    
3. R7 离成熟商用核的差距,**不是"能力差几倍"**,而是"开放研究核 vs 十年打磨商用 IP"的定位差,加上**一个明确的、可量化的、可修的面积债**。把 BPU 做对,这道账就改写了。
    

上一篇量了频率,这一篇量了面积;下一关,是把 BPU 这一刀真砍下去,再把核送进 P&R——真实的面积和频率,要到那时才算数。

CrossV 里每个人都在用自己的方法逼近 M7。把自己的核拉到综合服务器上、用门数对账、把 65% 的面积锁定到一个模块——这是我这次想给同行看的:**对标不是喊口号,是把核放到尺子下,看清楚每一 kGE 花在哪、哪一刀下去最值。**

---

  

  

阅读